### ISSUE TITLE
Clarification on PeptideMass, SpectrumMass and ppm calculation.

### ISSUE THREAD

**Issue by rajwanir** [ablab/npdtools#3]
Hello,

It seems a very useful set of tools. I had a few questions related to Dereplicator+ pipeline?

**What does 'PeptideMass' correspond to in significant_matches.tsv?**

Does it correspond to mass of the compound in database or that observed in spectra?  I am considering SpectrumMass  corresponds to mass of the precursor ion observed and PeptideMass corresponds to mass of the compound in database. If that is correct, the mass difference I see in significant_matches is higher than threshold (0.02 Da). Why would that be?

SpecFile | LocalSpecIdx | Scan | LocalPeptideIdx | Name | Score | PeptideMass | SpectrumMass | Retention | Adduct | Charge
a.mzXML | 422 | 196446 | 3236 | Heterobactin_A_Heterobactin_A | 26 | 615.229 | 616.237 | 196.438 | M+H | 1
a.mzXML | 1589 | 622491 | 1527 | Nocardimicin_Nocardimicin_D | 17 | 785.457 | 786.466 | 622.483 | M+H | 1

I am probably interpreting it wrong. Could you please clarify on PeptideMass and SpectrumMass  in this context and how ppm difference is computed?

 **Does Dereplicator+ pipeline uses number of amino acids from library.info in the compound database?**
I understand that the number of amino acids written in library info file is used in VarQuest pipeline as it accounts for modification. I wonder is it used in the Dereplicator+ too?

Thanks in advance.
Rahim.

**Comment by alexeigurevich** [comment]
Hello Rahim,
Sorry for the delay! Below are answers to all your questions.

>Does it correspond to mass of the compound in database or that observed in spectra? I am considering SpectrumMass corresponds to mass of the precursor ion observed and PeptideMass corresponds to mass of the compound in database. If that is correct, the mass difference I see in significant_matches is higher than threshold (0.02 Da). Why would that be?

You are right about both but for the precursor ion we actually report Mass-to-charge ratio (Mz; retrieved from experimental spectrum metadata) rather than estimated Mass, so it is shifted by 1.007276 Da if the adduct is M+H (the most common one and actually the only adduct of charge +1 supported by the current version of Dereplicator+). Sorry for the confusion. We followed the naming convention of [the MGF format](http://www.matrixscience.com/help/data_file_help.html) where PEPMASS of a spectrum is its Mz, not mass. We will improve the naming in future releases to make it more straightforward. I plan to use `CompoundMass` instead of `PeptideMass` since e.g. Dereplicator+ works not only with peptidic compounds and `SpectrumMZ` instead of `SpectrumMass`. Still, feel free to suggest your versions if you have other naming ideas and we will consider them.

>I am probably interpreting it wrong. Could you please clarify on PeptideMass and SpectrumMass in this context and how ppm difference is computed?

For clarification, see above. Regarding ppm, if you run the pipeline with `--ppm` (which is not a default behavior), we calculate the absolute error tolerance (in Da) for a given precursor or product ion as `ppm_value * ion_mz * ion_charge / 10**6`. For a precursor ion with Mz=1000 Da/e and charge=+1 and ppm value = 20 the allowed tolerance is 0.02 Da, while for a charged +1 product ion of 100 Da/e it would be just 0.002 Da. We mostly tested our pipelines with absolute tolerance errors, but ppm should also work fine.

> Does Dereplicator+ pipeline uses number of amino acids from library.info in the compound database?
I understand that the number of amino acids written in library info file is used in VarQuest pipeline as it accounts for modification. I wonder is it used in the Dereplicator+ too?

No, it is completely ignored by Dereplicator+. It is used by VarQuest and regular Dereplicator which are both designed for peptidic compounds (e.g. nonribosomal peptides). The former two pipelines ignore all compounds from the database that have less than 4 amino acids according to the corresponding library.info file. Here 4 is a default value and could be changed if needed.

--
I hope I've answered all your questions. Thank you for your interest in our tools. Let us know if you have any other questions or problems. You may also be interested in our new tool, [molDiscovery](https://cab.spbu.ru/software/molDiscovery/), which is an improvement over Dereplicator+. It is not released here yet but you can try its command-line beta-release or a web-version at GNPS (follow links from https://cab.spbu.ru/software/molDiscovery/). The preprint is also available from there.
